version: '3.5'
services:
  app:
    build:
      context: app/.
      dockerfile: Dockerfile
    container_name: gatsby-frontend
    volumes:
      - './app/src:/app/src'
      - './app/gatsby-config.js:/app/gatsby-config.js'
      - './resources/localhost+2.pem:/app/localhost+2.pem'
      - './resources/localhost+2-key.pem:/app/localhost+2-key.pem'
    ports:
      - '8000:8000'
      - '8001:8001'
    environment:
      NODE_ENV: development
    env_file:
      - ./.env
    command: >-
      npm run develop -- -H 0.0.0.0 --https --cert-file localhost+2.pem --key-file localhost+2-key.pem
  api:
    build:
      context: api/.
      dockerfile: Dockerfile
    container_name: az-functions
    depends_on:
      - app
    ports:
      - '7071:7071'
    volumes:
      - './api:/home/site/wwwroot/api'
      - './app/static/staticwebapp.config.json:/home/site/wwwroot/staticwebapp.config.json'
      - './resources/certificate.pfx:/home/site/wwwroot/certificate.pfx'
      - './resources/.password:/home/site/wwwroot/.password'
    env_file:
      - ./.env
    working_dir: /home/site/wwwroot/api
    command: >-
      func host start --cors * --useHttps --cert ../certificate.pfx --password ../.password
